//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birth_Cir
    {
        public int B_ID { get; set; }
        public Nullable<long> A_CNIC { get; set; }
        public string Relation { get; set; }
        public string C_Name { get; set; }
        public string F_Name { get; set; }
        public long F_CNIC_No { get; set; }
        public string M_Name { get; set; }
        public long M_CNIC_No { get; set; }
        public string Religion { get; set; }
        public string P_Adrs { get; set; }
        public string District { get; set; }
        public System.DateTime DOB { get; set; }
    }
}
