//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citizen_tbl
    {
        public int Citizen_id { get; set; }
        public string F_name { get; set; }
        public int curent_postal_code { get; set; }
        public string Email { get; set; }
        public string perm_house_no { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string date { get; set; }
        public string phone_no { get; set; }
        public Nullable<int> Cnic_Id { get; set; }
    
        public virtual cnic_info_tbl cnic_info_tbl { get; set; }
    }
}
