//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NadraDbContext : DbContext
    {
        public NadraDbContext()
            : base("name=NadraDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_tbl> account_tbl { get; set; }
        public virtual DbSet<citizen_tbl> citizen_tbl { get; set; }
        public virtual DbSet<cnic_info_tbl> cnic_info_tbl { get; set; }
        public virtual DbSet<invoice_tbl> invoice_tbl { get; set; }
        public virtual DbSet<login_tbl> login_tbl { get; set; }
        public virtual DbSet<payment_tbl> payment_tbl { get; set; }
        public virtual DbSet<staff_tbl> staff_tbl { get; set; }
    }
}
