//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_tbl
    {
        public int Payment_id { get; set; }
        public decimal charges { get; set; }
        public string payment_type { get; set; }
        public Nullable<int> Account_id { get; set; }
        public Nullable<int> cnic_id { get; set; }
    
        public virtual account_tbl account_tbl { get; set; }
        public virtual cnic_info_tbl cnic_info_tbl { get; set; }
    }
}
