//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff_tbl()
        {
            this.login_tbl = new HashSet<login_tbl>();
        }
    
        public int staff_id { get; set; }
        public string designation { get; set; }
        public string contact_staff { get; set; }
        public Nullable<int> cnic_id { get; set; }
    
        public virtual cnic_info_tbl cnic_info_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login_tbl> login_tbl { get; set; }
    }
}
