//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination_Cif
    {
        public int Vac_ID { get; set; }
        public string V_Name { get; set; }
        public int R_Dose { get; set; }
        public System.DateTime Dose1_Date { get; set; }
        public System.DateTime Dose2_Date { get; set; }
        public string Health_Center { get; set; }
        public string Manufacture { get; set; }
        public long Batch_NO_ { get; set; }
    }
}
